modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="lightningmod"
version="${version}"
displayName="lightningmod"
description='''A mod that increases the number of lightning strikes during thunderstorms.'''
iconFile="assets/lightningmod/icon.png"
authors="p4pingvin4ik"

[[mixins]]
config="lightningmod.mixins.json"

[[dependencies.lightningmod]]
modId="neoforge"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.lightningmod]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},${minecraft_version}.1)"
ordering="NONE"
side="BOTH"
